-- ===========================================================
-- V1 - Criação da tabela de beneficiários
-- ===========================================================
-- O banco é a fonte da verdade: tamanhos, NOT NULL e UNIQUE valem aqui,
-- e a Entity Beneficiario só espelha esses números.
-- Chave primária no padrão da disciplina: prefixo id_.
-- Depois do merge esta migration não pode mais ser editada, porque o
-- Flyway guarda o checksum dela na flyway_schema_history.

CREATE TABLE beneficiarios (
    id_beneficiario          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                     VARCHAR(150) NOT NULL,
    cpf                      VARCHAR(14)  NOT NULL UNIQUE,
    telefone                 VARCHAR(20),
    endereco                 VARCHAR(255),
    situacao_vulnerabilidade VARCHAR(500),
    data_cadastro            DATE         NOT NULL
);

-- Sem CREATE INDEX em cpf: a restrição UNIQUE já cria um índice nessa
-- coluna, no H2 e no PostgreSQL. Um segundo índice não aceleraria as
-- buscas e deixaria cada INSERT mais caro.
