-- ===========================================================
-- V2 - Criação da tabela de produtos (Avaliação A1)
-- ===========================================================
-- Número 2 porque é a próxima versão livre neste repositório (só existe a V1).
-- O banco é a fonte da verdade: as regras abaixo valem mesmo se alguém
-- gravar sem passar pela API, e a Entity Produto só espelha estes números.
-- Chave primária no padrão da disciplina: prefixo id_.

CREATE TABLE produtos (
    id_produto      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(150) NOT NULL UNIQUE,
    categoria       VARCHAR(20)  NOT NULL,
    estoque_atual   INT          NOT NULL,
    estoque_minimo  INT          NOT NULL,
    unidade_medida  VARCHAR(20)  NOT NULL,
    data_cadastro   DATE         NOT NULL,

    -- Última barreira contra estoque negativo; a API responde 422 antes disso.
    CONSTRAINT ck_produtos_estoque_atual  CHECK (estoque_atual >= 0),
    CONSTRAINT ck_produtos_estoque_minimo CHECK (estoque_minimo >= 0),
    -- Mesmos valores do enum CategoriaProduto (gravado como texto).
    CONSTRAINT ck_produtos_categoria
        CHECK (categoria IN ('ALIMENTO', 'ROUPA', 'HIGIENE', 'OUTROS'))
);

-- Sem CREATE INDEX em nome: a restrição UNIQUE já cria um índice nessa coluna.
